import type { Metadata } from "next";
import { Bebas_Neue, Montserrat } from 'next/font/google'
import "./globals.css";

const bebasNeue = Bebas_Neue({
  weight: '400', // Bebas Neue solo tiene un peso
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-bebas-neue',
})


const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
})

export const metadata: Metadata = {
  title: "Storm",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bebasNeue.variable} ${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
